#!/bin/bash

set -e

targetDevice="${1}"
hostname="${2}"
if [[ "${targetDevice}" = "" || "${hostname}" = "" ]]; then
	echo "Usage ${0} <target device> <hostname>" >&2
	exit 1
fi

echo "Building applications..."
make -C usr/src clean
make -C usr/src LINKER_SCRIPT=NanoOs.ld

# Make a temporary mountpoint
mountDir="$(mktemp -d)"
trap "rm -rf \"${mountDir}\"" ERR EXIT

echo ""
echo "Build complete."

sudo mkfs.exfat "${targetDevice}" -L NanoOs
sudo mount "${targetDevice}" "${mountDir}"
sudo mkdir -p "${mountDir}/etc"
sudo mkdir -p "${mountDir}/usr/bin"
sudo cp usr/bin/* "${mountDir}/usr/bin"
sudo bash -c "printf \"${hostname}\" >\"${mountDir}/etc/hostname\""
sudo bash -c "printf '\\s \\\r \\\n \\l\n\n' >\"${mountDir}/etc/issue\""
sudo umount "${mountDir}"

