#!/bin/bash

set -e

targetDevice="${1}"
if [ "${targetDevice}" = "" ]; then
	echo "Usage ${0} <target device>" >&2
	exit 1
fi

make -C usr/src

tempDir="$(mktemp -d)"
trap "rm -rf \"${tempDir}\"" ERR EXIT

sudo mkfs.exfat "${targetDevice}" -L NanoOs
sudo mount "${targetDevice}" "${tempDir}"
sudo mkdir -p "${tempDir}/etc"
sudo mkdir -p "${tempDir}/usr/bin"
sudo cp ${HOME}/Arduino/NanoOs/usr/bin/* "${tempDir}/usr/bin"
sudo bash -c "printf 'brian-nano33iot-1' >\"${tempDir}/etc/hostname\""
sudo bash -c "printf '\\s \\\r \\\n \\l\n\n' >\"${tempDir}/etc/issue\""
sudo umount "${tempDir}"

